# Generated by Django 4.0.4 on 2022-05-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_supportresponse_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'OK'), (2, 'NO'), (3, 'Frozen')], default=2, verbose_name='status of ticket'),
        ),
    ]
